// Tự động sinh bởi CapNhatNhanSu.bat
window.HR_DATA = {
  "active": [
    {
      "id": 3048826,
      "name": "Nguyễn Kim Tứ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "15/02/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1224,
      "monthsWorked": 40,
      "leaveReason": ""
    },
    {
      "id": 3039601,
      "name": "Từ Quang Nghĩa",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "02/10/2022",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1360,
      "monthsWorked": 44,
      "leaveReason": ""
    },
    {
      "id": 3039600,
      "name": "Nguyễn Tiền Nhân",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "02/10/2022",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1360,
      "monthsWorked": 44,
      "leaveReason": ""
    },
    {
      "id": 3059627,
      "name": "H Mưng Bkrông",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "27/06/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1092,
      "monthsWorked": 36,
      "leaveReason": ""
    },
    {
      "id": 1868009,
      "name": "Văn Thị Kim Thúy",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "29/04/2019",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 2612,
      "monthsWorked": 86,
      "leaveReason": ""
    },
    {
      "id": 3018838,
      "name": "Nguyễn Huỳnh Minh Thư",
      "dept": "Sorting Supervisor",
      "shift": "Ca 3",
      "joinDateStr": "23/12/2021",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1643,
      "monthsWorked": 54,
      "leaveReason": ""
    },
    {
      "id": 3000692,
      "name": "Tô Thùy Dung",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "02/03/2021",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1939,
      "monthsWorked": 63,
      "leaveReason": ""
    },
    {
      "id": 3048823,
      "name": "Bùi Thanh Ngân",
      "dept": "In/ Out Supervisor",
      "shift": "Ca 5",
      "joinDateStr": "15/02/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1224,
      "monthsWorked": 40,
      "leaveReason": ""
    },
    {
      "id": 3040929,
      "name": "Lê Thị Minh Hiền",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/10/2022",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1344,
      "monthsWorked": 44,
      "leaveReason": ""
    },
    {
      "id": 2033453,
      "name": "Phan Trọng Nhân",
      "dept": "In/ Out Supervisor",
      "shift": "Ca 3",
      "joinDateStr": "08/05/2020",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 2237,
      "monthsWorked": 73,
      "leaveReason": ""
    },
    {
      "id": 3067532,
      "name": "Nguyễn Thị Kim Hiền",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/09/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1022,
      "monthsWorked": 33,
      "leaveReason": ""
    },
    {
      "id": 3072857,
      "name": "Nguyễn Minh Thiện",
      "dept": "In/ Out Supervisor",
      "shift": "Ca 3",
      "joinDateStr": "16/10/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 981,
      "monthsWorked": 32,
      "leaveReason": ""
    },
    {
      "id": 3075239,
      "name": "Phạm Thị Kim Hạnh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/11/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 962,
      "monthsWorked": 31,
      "leaveReason": ""
    },
    {
      "id": 3076376,
      "name": "Lê Thị Như Ý",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/11/2023",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 954,
      "monthsWorked": 31,
      "leaveReason": ""
    },
    {
      "id": 3082865,
      "name": "Võ Công Nam",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "04/01/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 901,
      "monthsWorked": 29,
      "leaveReason": ""
    },
    {
      "id": 3083079,
      "name": "Phạm Văn Xuyên",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "06/01/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 899,
      "monthsWorked": 29,
      "leaveReason": ""
    },
    {
      "id": 3083678,
      "name": "Nguyễn Hồng Hưng",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/01/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 894,
      "monthsWorked": 29,
      "leaveReason": ""
    },
    {
      "id": 3083829,
      "name": "Mai Thành Trí",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/01/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 893,
      "monthsWorked": 29,
      "leaveReason": ""
    },
    {
      "id": 3088620,
      "name": "Nguyễn Duy Thanh",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/03/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 844,
      "monthsWorked": 27,
      "leaveReason": ""
    },
    {
      "id": 3088412,
      "name": "Trương Ngọc Sơn",
      "dept": "Sorting Supervisor",
      "shift": "Ca 3",
      "joinDateStr": "29/02/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 845,
      "monthsWorked": 28,
      "leaveReason": ""
    },
    {
      "id": 3090653,
      "name": "Phạm Lý Hùng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "13/03/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 832,
      "monthsWorked": 27,
      "leaveReason": ""
    },
    {
      "id": 3091048,
      "name": "Y Đăng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "16/03/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 829,
      "monthsWorked": 27,
      "leaveReason": ""
    },
    {
      "id": 3090780,
      "name": "Nguyễn Văn Hồng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/03/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 831,
      "monthsWorked": 27,
      "leaveReason": ""
    },
    {
      "id": 3091931,
      "name": "Nguyễn Văn Nghĩa",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/03/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 822,
      "monthsWorked": 27,
      "leaveReason": ""
    },
    {
      "id": 3093263,
      "name": "Phan Văn Cường",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "04/04/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 810,
      "monthsWorked": 26,
      "leaveReason": ""
    },
    {
      "id": 3094705,
      "name": "Mang Văn Tiền",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "19/04/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 795,
      "monthsWorked": 26,
      "leaveReason": ""
    },
    {
      "id": 3096064,
      "name": "Nguyễn Thúy Ngọc",
      "dept": "In/ Out Supervisor",
      "shift": "Ca 5",
      "joinDateStr": "05/05/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 779,
      "monthsWorked": 25,
      "leaveReason": ""
    },
    {
      "id": 3098491,
      "name": "Ngô Thị Ngọc Thao",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "30/05/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 754,
      "monthsWorked": 25,
      "leaveReason": ""
    },
    {
      "id": 3098865,
      "name": "Lê Hồ Kiệt",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "03/06/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 750,
      "monthsWorked": 24,
      "leaveReason": ""
    },
    {
      "id": 3100336,
      "name": "Nguyễn Thị Ngọc Trâm",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "21/06/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 732,
      "monthsWorked": 24,
      "leaveReason": ""
    },
    {
      "id": 3100735,
      "name": "Trương Xuân Định",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "26/06/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 727,
      "monthsWorked": 24,
      "leaveReason": ""
    },
    {
      "id": 3102481,
      "name": "Võ Trường Giang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/07/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 709,
      "monthsWorked": 23,
      "leaveReason": ""
    },
    {
      "id": 3108880,
      "name": "Thành Minh Hoàng ",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/09/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 647,
      "monthsWorked": 21,
      "leaveReason": ""
    },
    {
      "id": 3111373,
      "name": "Phạm Thị Kim Chi",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "09/10/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 622,
      "monthsWorked": 20,
      "leaveReason": ""
    },
    {
      "id": 3111663,
      "name": "Bùi Hữu Đức",
      "dept": "Sorting Supervisor",
      "shift": "Ca 3",
      "joinDateStr": "11/10/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 620,
      "monthsWorked": 20,
      "leaveReason": ""
    },
    {
      "id": 3111664,
      "name": "Mai Kim Duyên",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/10/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 620,
      "monthsWorked": 20,
      "leaveReason": ""
    },
    {
      "id": 3111894,
      "name": "Trương Quốc Khanh",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/10/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 617,
      "monthsWorked": 20,
      "leaveReason": ""
    },
    {
      "id": 3113405,
      "name": "Nguyễn Hữu Hiền",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "29/10/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 602,
      "monthsWorked": 20,
      "leaveReason": ""
    },
    {
      "id": 3100635,
      "name": "Hồ Ngọc Thiện",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "25/06/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 728,
      "monthsWorked": 24,
      "leaveReason": ""
    },
    {
      "id": 3113725,
      "name": "Trần Thị Loan",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 599,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3113720,
      "name": "Nguyễn Văn Nguyên",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 599,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3113772,
      "name": "Nguyễn Thị Bích Thủy",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 599,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3113782,
      "name": "Đặng Thanh Phong",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 599,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3114099,
      "name": "Ksor H'Hăn",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 596,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3114100,
      "name": "Ksor H' Lin",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 596,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3114299,
      "name": "Lý Hồng Phúc",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "09/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 591,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3115013,
      "name": "Lê Ngọc Thiên Trang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 588,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3115772,
      "name": "Nguyễn Quan Anh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "24/11/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 576,
      "monthsWorked": 19,
      "leaveReason": ""
    },
    {
      "id": 3119410,
      "name": "Nguyễn Văn Thuyện",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "26/12/2024",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 544,
      "monthsWorked": 18,
      "leaveReason": ""
    },
    {
      "id": 3120078,
      "name": "Lư Hồng Sang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/01/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 534,
      "monthsWorked": 17,
      "leaveReason": ""
    },
    {
      "id": 3120259,
      "name": "Lương Thị Minh Phương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "06/01/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 533,
      "monthsWorked": 17,
      "leaveReason": ""
    },
    {
      "id": 3125055,
      "name": "Lê Văn Quí",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "25/02/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 483,
      "monthsWorked": 16,
      "leaveReason": ""
    },
    {
      "id": 3126195,
      "name": "Võ Thị Mỹ Tho",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 475,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3126196,
      "name": "Lê Văn Dũng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 475,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3126807,
      "name": "Sơn Nanh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "10/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 470,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3127306,
      "name": "Đặng Thành Phát",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 466,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3127885,
      "name": "Nguyễn Thị Kim Chi",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "20/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 460,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3127917,
      "name": "Nguyễn Hoàng Nam",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "20/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 460,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3127919,
      "name": "Võ Vỹ Khang",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "20/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 460,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3128012,
      "name": "Võ Văn Sin",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "21/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 459,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3127884,
      "name": "Trần Thị Lan Phương",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 460,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3128573,
      "name": "Hoàng Thị Tính",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "27/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 453,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3128491,
      "name": "Nguyễn Hữu Ba",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "26/03/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 454,
      "monthsWorked": 15,
      "leaveReason": ""
    },
    {
      "id": 3130404,
      "name": "Nguyễn Kim Tiến",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/04/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 431,
      "monthsWorked": 14,
      "leaveReason": ""
    },
    {
      "id": 3130401,
      "name": "Nguyễn Văn Thừa",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/04/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 431,
      "monthsWorked": 14,
      "leaveReason": ""
    },
    {
      "id": 3129888,
      "name": "Nguyễn Thanh Bình",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/04/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 437,
      "monthsWorked": 14,
      "leaveReason": ""
    },
    {
      "id": 3130739,
      "name": "Đỗ Tuấn Vũ",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/04/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 426,
      "monthsWorked": 14,
      "leaveReason": ""
    },
    {
      "id": 3130860,
      "name": "Trần Bảo Minh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "24/04/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 425,
      "monthsWorked": 14,
      "leaveReason": ""
    },
    {
      "id": 3131589,
      "name": "Lý Trung Nhị",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "06/05/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 413,
      "monthsWorked": 13,
      "leaveReason": ""
    },
    {
      "id": 3131568,
      "name": "Lê Khải Triều",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "06/05/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 413,
      "monthsWorked": 13,
      "leaveReason": ""
    },
    {
      "id": 3132418,
      "name": "Nguyễn Ngọc Thơ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "15/05/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 404,
      "monthsWorked": 13,
      "leaveReason": ""
    },
    {
      "id": 3132016,
      "name": "Phan Văn Minh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/05/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 408,
      "monthsWorked": 13,
      "leaveReason": ""
    },
    {
      "id": 3133162,
      "name": "Trần Thị Duyên",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/05/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 396,
      "monthsWorked": 13,
      "leaveReason": ""
    },
    {
      "id": 3136041,
      "name": "Võ Nhật Hào ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "21/06/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 367,
      "monthsWorked": 12,
      "leaveReason": ""
    },
    {
      "id": 3135928,
      "name": "Nguyễn Thế Kiệt",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/06/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 368,
      "monthsWorked": 12,
      "leaveReason": ""
    },
    {
      "id": 3136773,
      "name": "Nguyễn Thị Quỳnh Trang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "02/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 356,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3137619,
      "name": "Phạm Minh Tuấn",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "11/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 347,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3137444,
      "name": "Thân Thanh Tùng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "10/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 348,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3137694,
      "name": "Nguyễn Thị Đan Phượng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "13/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 345,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3137730,
      "name": "Nguyễn Thị Thanh Hồng Phương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "13/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 345,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3138133,
      "name": "Phan Thanh Hạnh",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 341,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3138325,
      "name": "Nguyễn Thị Thanh Thảo",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 340,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3137691,
      "name": "Nguyễn Trọng Nhân",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "13/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 345,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3138786,
      "name": "Nguyễn Thị Phương Dung",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 335,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3138665,
      "name": "Nguyễn Văn Vũ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "22/07/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 336,
      "monthsWorked": 11,
      "leaveReason": ""
    },
    {
      "id": 3139577,
      "name": "Trần Thị Mỹ Lộc",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 326,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140004,
      "name": "Phạm Quang Vinh",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "06/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 321,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140393,
      "name": "Đào Thị Mộng Thu",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 316,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140392,
      "name": "Nguyễn Thanh Châu",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 316,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140907,
      "name": "Nguyễn Thanh Trường",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 313,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140914,
      "name": "Nguyễn Đông Quân",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 313,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3141010,
      "name": "Vũ Phước Thiên",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "15/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 312,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3141020,
      "name": "Lê Minh Hận",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "15/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 312,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3141022,
      "name": "Lê Thị Trắng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "15/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 312,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3141461,
      "name": "Trần Bảo Khang",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 307,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3140102,
      "name": "Lê Hoàng Vũ Hảo ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "07/08/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 320,
      "monthsWorked": 10,
      "leaveReason": ""
    },
    {
      "id": 3142822,
      "name": "Nguyễn Thị Thuỳ Trang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/09/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 291,
      "monthsWorked": 9,
      "leaveReason": ""
    },
    {
      "id": 3143983,
      "name": "Đặng Nguyễn Thúy Hạnh",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "13/09/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 283,
      "monthsWorked": 9,
      "leaveReason": ""
    },
    {
      "id": 3145283,
      "name": "Phùng Văn Trường ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "24/09/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 272,
      "monthsWorked": 9,
      "leaveReason": ""
    },
    {
      "id": 3145336,
      "name": "Quách Mạnh Hà",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "25/09/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 271,
      "monthsWorked": 9,
      "leaveReason": ""
    },
    {
      "id": 3144409,
      "name": "Trần Thanh Tú",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "16/09/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 280,
      "monthsWorked": 9,
      "leaveReason": ""
    },
    {
      "id": 3146223,
      "name": "Đặng Thị Thanh Phone",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 262,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3146936,
      "name": "Nguyễn Hữu Khương",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "10/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 256,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3147695,
      "name": "Nguyễn Lê Khang",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "17/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 249,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3147850,
      "name": "Huỳnh Thị Tú Trinh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "19/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 247,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3148336,
      "name": "Phan Thị Khoa ",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 243,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3148549,
      "name": "Lê Hoài Quốc Thắng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "25/10/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 241,
      "monthsWorked": 8,
      "leaveReason": ""
    },
    {
      "id": 3149557,
      "name": "Nguyễn Minh Thắng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "03/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 232,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3149974,
      "name": "Cao Thành Đạt",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "06/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 229,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3150778,
      "name": "Võ Thị Bích Hân ",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 221,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3151361,
      "name": "Trần Văn Hùng",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 217,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3151615,
      "name": "Nguyễn Thị Cô Thắm",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 215,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3151750,
      "name": "Trần Văn Chí Khương",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "21/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 214,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3151533,
      "name": "Nguyễn Văn Tùng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "19/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 216,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3151930,
      "name": "Lê Tấn Vinh",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "22/11/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 213,
      "monthsWorked": 7,
      "leaveReason": ""
    },
    {
      "id": 3153081,
      "name": "Ngô Quốc Thông",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "03/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 202,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3153253,
      "name": "Nguyễn Hồng Phi Yến",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "04/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 201,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3153275,
      "name": "Trương Thị Hồng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 201,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3153264,
      "name": "Nguyễn Thị Cindy",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "05/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 200,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3153781,
      "name": "Lê Thị Ánh Tuyết",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "09/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 196,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3153904,
      "name": "Nguyễn Thị Kiều",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "10/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 195,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3154682,
      "name": "Lâm Quốc Cường",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 187,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3154988,
      "name": "Nguyễn Trường Duy ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "22/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 183,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3154905,
      "name": "Lâm Mu Ni ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "22/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 183,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3155231,
      "name": "Quách Khả Ái Như",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "25/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 180,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3155069,
      "name": "Hồ Thị Thanh Thuỷ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 182,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3155628,
      "name": "Nguyễn Tấn Phong",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "31/12/2025",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 174,
      "monthsWorked": 6,
      "leaveReason": ""
    },
    {
      "id": 3155757,
      "name": "Nguyễn Thị Cẩm Ngân",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "02/01/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 172,
      "monthsWorked": 5,
      "leaveReason": ""
    },
    {
      "id": 3157328,
      "name": "Triệu Quốc An",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/01/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 154,
      "monthsWorked": 5,
      "leaveReason": ""
    },
    {
      "id": 3158631,
      "name": "Trương Kiều Nhiệm",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/02/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 123,
      "monthsWorked": 4,
      "leaveReason": ""
    },
    {
      "id": 3159178,
      "name": "Nguyễn Thị Lan",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "26/02/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 117,
      "monthsWorked": 4,
      "leaveReason": ""
    },
    {
      "id": 3159800,
      "name": "Ngô Thái Sơn",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 114,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3159794,
      "name": "Cao Quốc Khánh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 114,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3160539,
      "name": "Trịnh Nguyên Khang",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 111,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162296,
      "name": "Võ Cao Kỳ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 101,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162583,
      "name": "Lê Đăng Quang",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "16/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 99,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162511,
      "name": "Lâm Hữu Hậu",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "16/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 99,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162582,
      "name": "Võ Văn Chánh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 98,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162760,
      "name": "Phan Nguyễn Trung Thành",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "16/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 99,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162957,
      "name": "Cao Trường Giang",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "18/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 97,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3163260,
      "name": "Nguyễn Thị Hoằng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "20/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 95,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3163271,
      "name": "Phùng Xuân Vũ",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "20/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 95,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3164001,
      "name": "Nguyễn Thị Tập",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "25/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 90,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3162994,
      "name": "Nguyễn Văn Phước",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 92,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3164260,
      "name": "Huỳnh Thị Ngọc Tuyền",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "27/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 88,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3164261,
      "name": "Nguyễn Hoàng Phúc",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "27/03/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 88,
      "monthsWorked": 3,
      "leaveReason": ""
    },
    {
      "id": 3164928,
      "name": "Nguyễn Vũ Ẩn",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 83,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165038,
      "name": "Lâm Thị Phượng Uyên",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "02/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 82,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165353,
      "name": "Diệp Anh Khoa",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "05/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 79,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165166,
      "name": "Nguyễn Đoàn Thanh Vũ",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "03/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 81,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165760,
      "name": "Phạm Đức Trọng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "08/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 76,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165767,
      "name": "Tạ Thị Nương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "08/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 76,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3165768,
      "name": "Trần Vĩ Phương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "08/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 76,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3166557,
      "name": "Nguyễn Văn Khoẻ",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 70,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3166701,
      "name": "Nguyễn Văn Pháp",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "14/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 70,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167129,
      "name": "Lê Công Hậu",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "18/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 66,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167180,
      "name": "Bùi Quốc Thái",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "19/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 65,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167200,
      "name": "Nguyễn Tuấn Khang",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "19/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 65,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167057,
      "name": "Đỗ Xuân Quang",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 67,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167750,
      "name": "Trần Văn Tèo",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "23/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 61,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167898,
      "name": "Ngô Thái Bảo",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "24/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 60,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167903,
      "name": "Bùi Thanh Đạt",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "24/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 60,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3168141,
      "name": "Nguyễn Văn Nam",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "27/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 57,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3167899,
      "name": "Nguyễn Hoàng Thiện",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "27/04/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 57,
      "monthsWorked": 2,
      "leaveReason": ""
    },
    {
      "id": 3169083,
      "name": "Dương Thụy Ngọc Thảo",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "06/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 48,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169289,
      "name": "Nguyễn Thị Thảo My",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "07/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 47,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169135,
      "name": "Nguyễn Văn Thắng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "06/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 48,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169319,
      "name": "Đỗ Thị Lam",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "07/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 47,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169317,
      "name": "Vũ Thị Hoa",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "07/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 47,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169273,
      "name": "Lương Thế Vinh",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "07/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 47,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169299,
      "name": "Trần Đăng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "07/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 47,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3169846,
      "name": "Lê Thị Thuý An",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "11/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 43,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3170045,
      "name": "Nguyễn Thị Ngọc Lan",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 42,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3170048,
      "name": "Trần Thị Thuỳ Trang",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 42,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3170527,
      "name": "Vũ Bá Cương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "15/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 39,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3172001,
      "name": "Nguyễn Đức Bảo Ân",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "27/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 27,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3172263,
      "name": "Trương Thị Ngọc Tuyến",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "29/05/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 25,
      "monthsWorked": 1,
      "leaveReason": ""
    },
    {
      "id": 3172671,
      "name": "Nguyễn Hữu Phước",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172665,
      "name": "Lưu Thị Kim Cương ",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172658,
      "name": "Quách Văn Toàn",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172660,
      "name": "Trần Thanh Phúc",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172661,
      "name": "Lê Quang Nhẩn",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172687,
      "name": "Nguyễn Phúc Đại",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "01/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 22,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172912,
      "name": "Nguyễn Trần Nhựt Duy",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "02/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 21,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3172824,
      "name": "Nguyễn Thanh Tùng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "04/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 19,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3173342,
      "name": "Hoàng Công Hùng",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "06/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 17,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3173574,
      "name": "Đoàn Thành Nghiệp",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "08/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 15,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3173641,
      "name": "Huỳnh Chí Kha",
      "dept": "Sorting Staff",
      "shift": "Ca 3",
      "joinDateStr": "08/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 15,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3174417,
      "name": "Trịnh Tiến Dũng",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 9,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3174416,
      "name": "Nguyễn Thu Hiểu",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "14/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 9,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3175693,
      "name": "Phan Ngọc Diễm",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "22/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 1,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3175574,
      "name": "Trần Thanh Tuấn",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "21/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 2,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3174151,
      "name": "Cao Trọng Phúc",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "12/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 11,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3175010,
      "name": "Huỳnh Công Danh",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 6,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3175006,
      "name": "Nguyễn Thị Ngọc Như",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 6,
      "monthsWorked": 0,
      "leaveReason": ""
    },
    {
      "id": 3175024,
      "name": "Thị Dân",
      "dept": "In/ Out Staff",
      "shift": "Ca 3",
      "joinDateStr": "17/06/2026",
      "leaveDateStr": "",
      "status": "Đang làm việc",
      "daysWorked": 6,
      "monthsWorked": 0,
      "leaveReason": ""
    }
  ],
  "resigned": [
    {
      "id": 3168217,
      "name": "Võ Ngọc Thùy Dương",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "28/04/2026",
      "leaveDateStr": "15/06/2026",
      "status": "Đã nghỉ việc",
      "daysWorked": 48,
      "monthsWorked": 2,
      "leaveReason": "Nghỉ ngang"
    },
    {
      "id": 3170982,
      "name": "Nguyễn Hoàng Nhân",
      "dept": "In/ Out Staff",
      "shift": "Ca 5",
      "joinDateStr": "19/05/2026",
      "leaveDateStr": "20/06/2026",
      "status": "Đã nghỉ việc",
      "daysWorked": 32,
      "monthsWorked": 1,
      "leaveReason": "Về quê"
    }
  ]
};
